// <auto-generated />
using System;
using System.Collections.Generic;
using LoreWeaver.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoreWeaver.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loreweaver")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoreWeaver.Entities.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Coordinate", "loreweaver");
                });

            modelBuilder.Entity("LoreWeaver.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime?>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lore")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Resources")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("shortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentLocationId");

                    b.ToTable("Location", "loreweaver");

                    b.HasDiscriminator().HasValue("Location");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LoreWeaver.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.PrimitiveCollection<int[]>("Roles")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "loreweaver");
                });

            modelBuilder.Entity("LoreWeaver.Entities.World", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MapPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Worlds", "loreweaver");
                });

            modelBuilder.Entity("LoreWeaver.Entities.GeographicLocation", b =>
                {
                    b.HasBaseType("LoreWeaver.Entities.Location");

                    b.Property<int?>("GeographicLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("GeographicType")
                        .HasColumnType("integer");

                    b.Property<int?>("PoliticalLocationId")
                        .HasColumnType("integer");

                    b.Property<int>("WorldId")
                        .HasColumnType("integer");

                    b.HasIndex("GeographicLocationId");

                    b.HasIndex("PoliticalLocationId");

                    b.HasIndex("WorldId");

                    b.HasDiscriminator().HasValue("GeographicLocation");
                });

            modelBuilder.Entity("LoreWeaver.Entities.PoliticalLocation", b =>
                {
                    b.HasBaseType("LoreWeaver.Entities.Location");

                    b.Property<string>("GovernmentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PoliticalType")
                        .HasColumnType("integer");

                    b.Property<string>("Ruler")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorldId")
                        .HasColumnType("integer");

                    b.HasIndex("WorldId");

                    b.ToTable("Location", "loreweaver", t =>
                        {
                            t.Property("WorldId")
                                .HasColumnName("PoliticalLocation_WorldId");
                        });

                    b.HasDiscriminator().HasValue("PoliticalLocation");
                });

            modelBuilder.Entity("LoreWeaver.Entities.Coordinate", b =>
                {
                    b.HasOne("LoreWeaver.Entities.Location", null)
                        .WithMany("Coordinates")
                        .HasForeignKey("LocationId");
                });

            modelBuilder.Entity("LoreWeaver.Entities.Location", b =>
                {
                    b.HasOne("LoreWeaver.Entities.Location", "ParentLocation")
                        .WithMany("Subdivisions")
                        .HasForeignKey("ParentLocationId");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("LoreWeaver.Entities.World", b =>
                {
                    b.HasOne("LoreWeaver.Entities.User", "User")
                        .WithMany("Worlds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LoreWeaver.Entities.GeographicLocation", b =>
                {
                    b.HasOne("LoreWeaver.Entities.GeographicLocation", null)
                        .WithMany("ConnectedAreas")
                        .HasForeignKey("GeographicLocationId");

                    b.HasOne("LoreWeaver.Entities.PoliticalLocation", null)
                        .WithMany("GeographicTerritories")
                        .HasForeignKey("PoliticalLocationId");

                    b.HasOne("LoreWeaver.Entities.World", "World")
                        .WithMany("GeographicLocations")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("LoreWeaver.Entities.PoliticalLocation", b =>
                {
                    b.HasOne("LoreWeaver.Entities.World", "World")
                        .WithMany("PoliticalLocations")
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("LoreWeaver.Entities.Location", b =>
                {
                    b.Navigation("Coordinates");

                    b.Navigation("Subdivisions");
                });

            modelBuilder.Entity("LoreWeaver.Entities.User", b =>
                {
                    b.Navigation("Worlds");
                });

            modelBuilder.Entity("LoreWeaver.Entities.World", b =>
                {
                    b.Navigation("GeographicLocations");

                    b.Navigation("PoliticalLocations");
                });

            modelBuilder.Entity("LoreWeaver.Entities.GeographicLocation", b =>
                {
                    b.Navigation("ConnectedAreas");
                });

            modelBuilder.Entity("LoreWeaver.Entities.PoliticalLocation", b =>
                {
                    b.Navigation("GeographicTerritories");
                });
#pragma warning restore 612, 618
        }
    }
}
